# Generated by Django 3.2.5 on 2021-09-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210907_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='create_date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
