# Generated by Django 3.2.5 on 2021-09-09 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210909_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='publicDate',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 9, 9, 22, 8, 28, 698416)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='hotDate',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 9, 9, 22, 8, 28, 698416)),
        ),
    ]
