# Generated by Django 3.2.5 on 2021-09-12 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20210911_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='hotDate',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 9, 12, 14, 6, 53, 929451)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publicDate',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 9, 12, 14, 6, 53, 928451)),
        ),
    ]
