# Generated by Django 3.2.5 on 2021-09-14 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210913_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 9, 12, 0, 0)),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 9, 12, 0, 0)),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
