# Generated by Django 3.2.5 on 2021-11-11 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210915_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2021, 11, 11, 15, 33, 43, 425456, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2021, 11, 11, 15, 33, 43, 425456, tzinfo=utc)),
        ),
    ]
