# Generated by Django 3.2.5 on 2021-11-11 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20211112_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(auto_created=True, default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(auto_created=True, default=datetime.date(2000, 1, 1)),
        ),
    ]
