# Generated by Django 3.2.5 on 2021-08-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('grade', models.IntegerField()),
                ('room', models.IntegerField()),
                ('number', models.IntegerField()),
                ('regi_date', models.DateField()),
            ],
        ),
    ]
