# Generated by Django 3.2.5 on 2021-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210811_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastedit',
            field=models.DateField(auto_now=True),
        ),
    ]
