# Generated by Django 3.2.5 on 2021-08-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210814_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interested_in',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_message',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
