# Generated by Django 3.2.5 on 2021-09-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210814_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='regi_date',
            field=models.DateField(auto_created=True),
        ),
    ]
