# Generated by Django 3.2.5 on 2021-09-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210908_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
