# Generated by Django 3.2.5 on 2021-09-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_user_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isactive',
        ),
    ]
