# Generated by Django 3.2.5 on 2021-10-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_userloginlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginlog',
            name='updated',
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='created',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
