# Generated by Django 3.2.5 on 2021-10-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20211031_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloginlog',
            options={},
        ),
        migrations.RenameField(
            model_name='userloginlog',
            old_name='created',
            new_name='logged',
        ),
    ]
