# Generated by Django 3.2.5 on 2021-10-31 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20211031_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginlog',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='userloginlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
