# Generated by Django 3.2.5 on 2021-11-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20211112_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like',
            field=models.TextField(blank=True, default='/', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='noticelike',
            field=models.TextField(blank=True, default='/', null=True),
        ),
    ]
