# Generated by Django 3.2.5 on 2021-11-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211112_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='like',
            field=models.TextField(blank=True, default='/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='noticelike',
            field=models.TextField(blank=True, default='/'),
        ),
    ]
