# Generated by Django 3.2.5 on 2021-07-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('member', models.IntegerField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
