# Generated by Django 3.2.5 on 2021-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(default='기타', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='isofficial',
            field=models.BooleanField(default=False),
        ),
    ]
