# Generated by Django 3.2.5 on 2021-08-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_club_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_master',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='club_teacher',
            field=models.CharField(default='', max_length=20),
        ),
    ]
