# Generated by Django 3.2.5 on 2021-08-05 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_year'),
        ('club', '0004_auto_20210803_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_thumbnail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='home.user'),
        ),
    ]
