# Generated by Django 3.2.5 on 2021-08-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20210805_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='member_detail',
            field=models.TextField(default=''),
        ),
    ]
