# Generated by Django 3.2.5 on 2021-09-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_club_member_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='create_date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='member',
            field=models.IntegerField(default=1),
        ),
    ]
