# Generated by Django 3.2.5 on 2021-10-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_auto_20210908_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
