# Generated by Django 3.2.5 on 2021-10-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_club_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='appli',
            field=models.TextField(default=''),
        ),
    ]
