# Generated by Django 3.2.5 on 2021-11-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_auto_20211112_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='appli',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='member_detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
